import type { Metadata } from "next";
import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { brand } from "@/lib/content";
import { siteUrl } from "@/lib/seo";

/* ── Company details — edit here ─────────────────────────────── */
const COMPANY = "ITC ECOM LLC";
const STATE = "Wyoming";
const ADDRESS = "30 N Gould St STE N, Sheridan, WY 82801, USA";
const ARBITRATION_VENUE = "Sheridan, Wyoming";
const EMAIL = "hello@upsidegpt.com";
const SITE_DOMAIN = "upsidegpt.com";
const FORMED = "November 2025";
const EFFECTIVE = "June 1, 2026";
const GOVERNING_ACT = "Wyoming Limited Liability Company Act, Wyo. Stat. Ann. §§ 17-29-101 et seq.";
// Optional — fill in once available, then they render automatically:
const ENTITY_ID = ""; // e.g. "2025-001234567"
const REGISTERED_AGENT = ""; // e.g. "Registered Agents Inc"
const PAYMENT_PROCESSOR = "our third-party payment processor"; // e.g. "Stripe" / "Whop.com"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `The terms governing your use of ${brand.name}, operated by ${COMPANY}.`,
  alternates: { canonical: `${siteUrl}/terms-of-service` },
};

function Article({ n, title, children }: { n: number; title: string; children: ReactNode }) {
  return (
    <section className="mt-10 border-t border-white/10 pt-10">
      <h2 className="text-lg font-bold tracking-tight text-white sm:text-xl">
        <span className="text-neutral-500">Article {n} —</span> {title}
      </h2>
      <div className="mt-4 space-y-4 text-[15px] leading-7 text-neutral-400 [&_a]:text-accent [&_a]:underline [&_a]:underline-offset-2 [&_li]:pl-1 [&_strong]:font-semibold [&_strong]:text-neutral-200 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-5 [&_ul]:marker:text-neutral-600">
        {children}
      </div>
    </section>
  );
}

function Sub({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="pt-1">
      <h3 className="text-[15px] font-semibold text-neutral-200">{title}</h3>
      <div className="mt-1.5 space-y-3">{children}</div>
    </div>
  );
}

export default function TermsOfService() {
  return (
    <main>
      <Navbar />
      <article className="mx-auto max-w-3xl px-5 py-16 sm:py-24">
        <header className="border-b border-white/10 pb-10 text-center">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Legal</p>
          <h1 className="mt-4 text-4xl font-bold tracking-tight text-white sm:text-5xl">Terms of Service</h1>
          <p className="mt-5 text-sm text-neutral-400">{brand.name} — AI Stock Analysis Platform</p>
          <p className="mt-1 text-sm text-neutral-500">{COMPANY} · Effective: {EFFECTIVE}</p>
        </header>

        <div className="mt-10 rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-[13px] font-semibold uppercase leading-6 tracking-wide text-neutral-300">
          Please read these Terms of Service carefully before accessing or using {SITE_DOMAIN}. By creating an account or
          purchasing a plan, you agree to be legally bound by these Terms.
        </div>

        <Article n={1} title="Identification of the Publisher">
          <p>
            The website {SITE_DOMAIN} (the <strong>&ldquo;Platform&rdquo;</strong>) is published and operated by{" "}
            {COMPANY}, a limited liability company organized under the laws of the State of {STATE}, United States of
            America.
          </p>
          <ul>
            <li><strong>Formation date:</strong> {FORMED}</li>
            {ENTITY_ID && <li><strong>Entity ID:</strong> {ENTITY_ID}</li>}
            <li><strong>Principal place of business:</strong> {ADDRESS}</li>
            {REGISTERED_AGENT && <li><strong>Registered Agent:</strong> {REGISTERED_AGENT}</li>}
            <li><strong>Contact:</strong> <a href={`mailto:${EMAIL}`}>{EMAIL}</a></li>
            <li><strong>Governing statute:</strong> {GOVERNING_ACT}</li>
          </ul>
        </Article>

        <Article n={2} title="Definitions">
          <ul>
            <li><strong>&ldquo;Platform&rdquo;</strong> means the website {SITE_DOMAIN} and all associated services, tools, and content.</li>
            <li><strong>&ldquo;Service&rdquo;</strong> means the AI-powered stock-chart analysis tool and any related features provided by {brand.name}.</li>
            <li><strong>&ldquo;User&rdquo;</strong> or <strong>&ldquo;Subscriber&rdquo;</strong> means any individual or entity who creates an account or purchases a plan.</li>
            <li><strong>&ldquo;Subscription&rdquo;</strong> means recurring monthly paid access to the Service.</li>
            <li><strong>&ldquo;Lifetime Access&rdquo;</strong> means one-time paid access to the Service for the lifetime of the Service.</li>
            <li><strong>&ldquo;Content&rdquo;</strong> or <strong>&ldquo;Output&rdquo;</strong> means any analysis, signal, score, level, scenario, or information generated by the Service.</li>
            <li><strong>&ldquo;Affiliate Content&rdquo;</strong> means any sponsored, partnership, or affiliate-linked content we publish on any channel.</li>
          </ul>
        </Article>

        <Article n={3} title="Description of Services">
          <p>
            {brand.name} operates an AI-powered software-as-a-service platform that analyzes stock charts and generates
            technical and fundamental analysis outputs, including trend, key levels, indicators, signals, probability
            scenarios, and related market context. The Service is provided strictly as an informational and educational
            tool.
          </p>
          <p>
            {brand.name} may also publish educational content, information products, and affiliate-linked recommendations
            on its website and social-media channels. All such content is clearly identified where required by
            applicable law.
          </p>
          <p>
            <strong>
              The Service does not constitute financial advice, investment advice, trading advice, or any other type of
              professional advice. See Article 8.
            </strong>
          </p>
        </Article>

        <Article n={4} title="Subscription & Payment Terms">
          <p>
            Access to the Service requires a paid plan. {brand.name} currently offers a monthly Subscription (USD 40.00
            per month, or the price displayed at the time of purchase) and a one-time Lifetime Access plan (USD 180.00,
            or the price displayed at checkout). Payments are processed through {PAYMENT_PROCESSOR}.
          </p>
          <Sub title="4.1 Billing">
            <p>
              Subscription fees are billed automatically on the same date each billing period. By subscribing, the User
              authorizes {COMPANY} and {PAYMENT_PROCESSOR} to charge the designated payment method on a recurring basis
              until cancellation. Lifetime Access is charged once at the time of purchase.
            </p>
          </Sub>
          <Sub title="4.2 Price Changes">
            <p>
              {COMPANY} reserves the right to modify pricing upon fourteen (14) days&rsquo; prior notice. Continued use
              of the Service after the effective date of a price change constitutes acceptance of the new price. Price
              changes do not affect the current paid period.
            </p>
          </Sub>
          <Sub title="4.3 Failed Payments">
            <p>
              If a recurring payment fails, access to the Service may be suspended immediately. The User is responsible
              for maintaining valid and current payment information.
            </p>
          </Sub>
          <Sub title="4.4 Taxes">
            <p>
              All prices are exclusive of applicable taxes. The User is responsible for any applicable taxes, VAT, or
              duties owed in their jurisdiction.
            </p>
          </Sub>
        </Article>

        <Article n={5} title="Refund Policy">
          <p>
            <strong>All sales are final. {COMPANY} maintains a strict no-refund policy as a general rule.</strong> By
            completing a purchase, the User expressly acknowledges and agrees that fees are non-refundable except in the
            two (2) strictly limited circumstances described below.
          </p>
          <Sub title="5.1 Eligible refund circumstances">
            <p>A refund request will be considered only if all of the applicable conditions are met:</p>
            <p>
              <strong>(a) Total platform outage — technical malfunction.</strong> The User must demonstrate, with
              timestamped screenshot evidence, error logs, and written confirmation from {brand.name} support, that the
              Platform was completely non-functional and inaccessible for a continuous period of twenty-four (24) or more
              consecutive hours. Partial degradation, slow performance, or dissatisfaction with Output quality does not
              qualify. The User must have reported the issue to <a href={`mailto:${EMAIL}`}>{EMAIL}</a> within forty-eight
              (48) hours of the incident and obtained a support ticket number. Retroactive claims are not accepted.
            </p>
            <p>
              <strong>(b) Verified duplicate charge.</strong> The User must provide official bank or payment-processor
              records clearly showing two identical charges for the same period, copies of both transaction
              confirmations, and must submit the request within seven (7) calendar days of the duplicate charge. Only the
              duplicate amount is refundable; the original charge is non-refundable.
            </p>
          </Sub>
          <Sub title="5.2 Non-eligible circumstances — no exceptions">
            <ul>
              <li>change of mind or dissatisfaction with AI-generated analyses, signals, or Output;</li>
              <li>financial or trading losses incurred from decisions made using the Platform;</li>
              <li>failure to cancel a Subscription before the next billing cycle;</li>
              <li>partial use of the Service during a billing period;</li>
              <li>incompatibility with the User&rsquo;s device or internet connection;</li>
              <li>dissatisfaction with features, updates, or changes to the Service;</li>
              <li>claims submitted more than seven (7) calendar days after the disputed charge.</li>
            </ul>
          </Sub>
          <Sub title="5.3 Refund request procedure">
            <p>
              All refund requests must be submitted in writing to <a href={`mailto:${EMAIL}`}>{EMAIL}</a> with the subject
              line &ldquo;REFUND REQUEST — [Transaction ID]&rdquo; and must include the User&rsquo;s full name, account
              email, transaction ID, the nature of the claim, and all supporting evidence. {COMPANY} will review requests
              within ten (10) business days; approval is at its sole discretion.
            </p>
          </Sub>
          <Sub title="5.4 Chargebacks">
            <p>
              Any unauthorized chargeback or payment dispute initiated without following the procedure above will result
              in immediate and permanent account termination without notice, and may be pursued for damages,
              administrative fees, and collection costs.
            </p>
          </Sub>
        </Article>

        <Article n={6} title="User Obligations & Acceptable Use">
          <p>By using the Platform, the User agrees to:</p>
          <ul>
            <li>provide accurate, current, and complete registration information;</li>
            <li>maintain the confidentiality of account credentials and remain responsible for all activity under the account;</li>
            <li>not share, resell, or transfer their access to any third party;</li>
            <li>not scrape, copy, reverse-engineer, or reproduce any Output or Platform content for commercial purposes;</li>
            <li>not use the Platform for any unlawful purpose or in violation of applicable regulations;</li>
            <li>comply with all financial and other regulations applicable in their jurisdiction.</li>
          </ul>
          <p>
            {COMPANY} reserves the right to suspend or terminate any account found in violation of these obligations,
            without refund or prior notice.
          </p>
        </Article>

        <Article n={7} title="Intellectual Property">
          <p>
            All content, software, algorithms, models, brand elements, analyses, and materials on the Platform are the
            exclusive intellectual property of {COMPANY} or its licensors. No license to any intellectual property is
            granted to the User other than a limited, non-exclusive, non-transferable, revocable right to access the
            Service for personal, non-commercial use during an active paid period. All rights not expressly granted are
            reserved.
          </p>
        </Article>

        <Article n={8} title="Disclaimer of Financial Advice & Limitation of Liability">
          <p className="uppercase">
            The Platform and all Content generated by {brand.name} are for informational and educational purposes only.
            Nothing on {SITE_DOMAIN} or any associated channel constitutes financial advice, investment advice, trading
            recommendations, or any form of regulated financial service.
          </p>
          <p className="uppercase">
            {COMPANY}, its officers, members, employees, and affiliates shall not be liable for any direct, indirect,
            incidental, special, consequential, or punitive damages arising from: (i) use of or inability to use the
            Service; (ii) trading or investment decisions made based on Platform Content; (iii) loss of profits, data, or
            goodwill; or (iv) any unauthorized access to or alteration of User data.
          </p>
          <p className="uppercase">
            To the maximum extent permitted by applicable law, {COMPANY}&rsquo;s total liability shall not exceed the
            amount paid by the User to {COMPANY} in the thirty (30) days preceding the event giving rise to the claim.
          </p>
        </Article>

        <Article n={9} title="Affiliate Disclosure">
          <p>
            {brand.name} may publish affiliate links, sponsored content, or partnership recommendations on {SITE_DOMAIN}{" "}
            and associated social-media channels. Where compensation is received in exchange for a promotion, this will
            be disclosed in compliance with the U.S. Federal Trade Commission (FTC) Endorsement Guidelines (16 CFR Part
            255). Affiliate relationships do not influence the editorial independence of {brand.name}&rsquo;s analysis
            tools.
          </p>
        </Article>

        <Article n={10} title="Privacy & Data Protection">
          <p>
            The collection and processing of personal data is governed by {brand.name}&rsquo;s Privacy Policy, available
            at {SITE_DOMAIN}/privacy-policy. By using the Service, the User consents to the data practices described
            therein.
          </p>
        </Article>

        <Article n={11} title="Modifications to the Service & Terms">
          <p>
            {COMPANY} reserves the right to modify, suspend, or discontinue the Service at any time. These Terms may be
            updated periodically. The User will be notified of material changes by email or by a notice on the Platform.
            Continued use of the Service after notification constitutes acceptance of the revised Terms.
          </p>
        </Article>

        <Article n={12} title="Governing Law & Dispute Resolution">
          <p>
            These Terms are governed by the laws of the State of {STATE}, United States of America, without regard to
            conflict-of-law principles.
          </p>
          <p>
            Any dispute arising from these Terms shall first be submitted to good-faith negotiation. Failing resolution
            within thirty (30) days, the dispute shall be submitted to binding arbitration in {ARBITRATION_VENUE}, under
            the rules of the American Arbitration Association (AAA). The User waives any right to participate in a class
            action lawsuit or class-wide arbitration.
          </p>
        </Article>

        <Article n={13} title="Contact">
          <p>For any questions regarding these Terms, please contact:</p>
          <p>
            {COMPANY} — {brand.name} Legal
            <br />
            {ADDRESS}
            <br />
            Email: <a href={`mailto:${EMAIL}`}>{EMAIL}</a>
            <br />
            Website: <a href={siteUrl}>{SITE_DOMAIN}</a>
          </p>
        </Article>

        <p className="mt-10 border-t border-white/10 pt-8 text-center text-xs text-neutral-500">
          Last updated: {EFFECTIVE} — {COMPANY}, all rights reserved.
        </p>
      </article>
      <Footer />
    </main>
  );
}
